#mpa_v30_CHOCOPhlAn_201901
#/home/vancampn/miniconda3/bin/metaphlan /data/metamixer/ASF_metamixer.fastq.gz --input_type fastq --bowtie2out /data/metaphlan/ASF_metamixer_bowtie2.bz2 -o /data/metaphlan/ASF_metamixer.out
#SampleID	Metaphlan_Analysis
#clade_name	NCBI_tax_id	relative_abundance	additional_species
k__Bacteria	2	100.0	
k__Bacteria|p__Firmicutes	2|1239	71.93355	
k__Bacteria|p__Deferribacteres	2|200930	23.2072	
k__Bacteria|p__Bacteroidetes	2|976	4.85925	
k__Bacteria|p__Firmicutes|c__Clostridia	2|1239|186801	70.12986	
k__Bacteria|p__Deferribacteres|c__Deferribacteres	2|200930|68337	23.2072	
k__Bacteria|p__Bacteroidetes|c__Bacteroidia	2|976|200643	4.85925	
k__Bacteria|p__Firmicutes|c__Firmicutes_unclassified	2|1239|	1.69013	
k__Bacteria|p__Firmicutes|c__Bacilli	2|1239|91061	0.11356	
k__Bacteria|p__Firmicutes|c__Clostridia|o__Clostridiales	2|1239|186801|186802	70.12986	
k__Bacteria|p__Deferribacteres|c__Deferribacteres|o__Deferribacterales	2|200930|68337|191393	23.2072	
k__Bacteria|p__Bacteroidetes|c__Bacteroidia|o__Bacteroidales	2|976|200643|171549	4.85925	
k__Bacteria|p__Firmicutes|c__Firmicutes_unclassified|o__Firmicutes_unclassified	2|1239||	1.69013	
k__Bacteria|p__Firmicutes|c__Bacilli|o__Lactobacillales	2|1239|91061|186826	0.11356	
k__Bacteria|p__Firmicutes|c__Clostridia|o__Clostridiales|f__Clostridiaceae	2|1239|186801|186802|31979	51.24612	
k__Bacteria|p__Deferribacteres|c__Deferribacteres|o__Deferribacterales|f__Deferribacteraceae	2|200930|68337|191393|191394	23.2072	
k__Bacteria|p__Firmicutes|c__Clostridia|o__Clostridiales|f__Eubacteriaceae	2|1239|186801|186802|186806	18.88374	
k__Bacteria|p__Bacteroidetes|c__Bacteroidia|o__Bacteroidales|f__Tannerellaceae	2|976|200643|171549|2005525	4.85925	
k__Bacteria|p__Firmicutes|c__Firmicutes_unclassified|o__Firmicutes_unclassified|f__Firmicutes_unclassified	2|1239|||	1.69013	
k__Bacteria|p__Firmicutes|c__Bacilli|o__Lactobacillales|f__Lactobacillaceae	2|1239|91061|186826|33958	0.11356	
k__Bacteria|p__Firmicutes|c__Clostridia|o__Clostridiales|f__Clostridiaceae|g__Clostridium	2|1239|186801|186802|31979|1485	51.24612	
k__Bacteria|p__Deferribacteres|c__Deferribacteres|o__Deferribacterales|f__Deferribacteraceae|g__Mucispirillum	2|200930|68337|191393|191394|248038	23.2072	
k__Bacteria|p__Firmicutes|c__Clostridia|o__Clostridiales|f__Eubacteriaceae|g__Eubacterium	2|1239|186801|186802|186806|1730	18.88374	
k__Bacteria|p__Bacteroidetes|c__Bacteroidia|o__Bacteroidales|f__Tannerellaceae|g__Parabacteroides	2|976|200643|171549|2005525|375288	4.85925	
k__Bacteria|p__Firmicutes|c__Firmicutes_unclassified|o__Firmicutes_unclassified|f__Firmicutes_unclassified|g__Firmicutes_unclassified	2|1239||||	1.69013	
k__Bacteria|p__Firmicutes|c__Bacilli|o__Lactobacillales|f__Lactobacillaceae|g__Lactobacillus	2|1239|91061|186826|33958|1578	0.11356	
k__Bacteria|p__Firmicutes|c__Clostridia|o__Clostridiales|f__Clostridiaceae|g__Clostridium|s__Clostridium_sp_ASF502	2|1239|186801|186802|31979|1485|97139	35.74813	
k__Bacteria|p__Deferribacteres|c__Deferribacteres|o__Deferribacterales|f__Deferribacteraceae|g__Mucispirillum|s__Mucispirillum_schaedleri	2|200930|68337|191393|191394|248038|248039	23.2072	
k__Bacteria|p__Firmicutes|c__Clostridia|o__Clostridiales|f__Eubacteriaceae|g__Eubacterium|s__Eubacterium_plexicaudatum	2|1239|186801|186802|186806|1730|97253	18.88374	
k__Bacteria|p__Firmicutes|c__Clostridia|o__Clostridiales|f__Clostridiaceae|g__Clostridium|s__Clostridium_sp_ASF356	2|1239|186801|186802|31979|1485|97138	15.49799	
k__Bacteria|p__Bacteroidetes|c__Bacteroidia|o__Bacteroidales|f__Tannerellaceae|g__Parabacteroides|s__Parabacteroides_goldsteinii	2|976|200643|171549|2005525|375288|328812	4.85925	k__Bacteria|p__Bacteroidetes|c__Bacteroidia|o__Bacteroidales|f__Tannerellaceae|g__Parabacteroides|s__Parabacteroides_sp_ASF519
k__Bacteria|p__Firmicutes|c__Firmicutes_unclassified|o__Firmicutes_unclassified|f__Firmicutes_unclassified|g__Firmicutes_unclassified|s__Firmicutes_bacterium_ASF500	2|1239|||||1378168	1.69013	
k__Bacteria|p__Firmicutes|c__Bacilli|o__Lactobacillales|f__Lactobacillaceae|g__Lactobacillus|s__Lactobacillus_murinus	2|1239|91061|186826|33958|1578|1622	0.11356	
