#mpa_v30_CHOCOPhlAn_201901
#/home/vancampn/miniconda3/bin/metaphlan /data/grinder/ASF_grinder.fastq.gz --input_type fastq --bowtie2out /data/metaphlan/ASF_grinder_bowtie2.bz2 -o /data/metaphlan/ASF_grinder.mf
#SampleID	Metaphlan_Analysis
#clade_name	NCBI_tax_id	relative_abundance	additional_species
k__Bacteria	2	100.0	
k__Bacteria|p__Firmicutes	2|1239	41.47492	
k__Bacteria|p__Bacteroidetes	2|976	30.05768	
k__Bacteria|p__Deferribacteres	2|200930	28.4674	
k__Bacteria|p__Firmicutes|c__Clostridia	2|1239|186801	40.10551	
k__Bacteria|p__Bacteroidetes|c__Bacteroidia	2|976|200643	30.05768	
k__Bacteria|p__Deferribacteres|c__Deferribacteres	2|200930|68337	28.4674	
k__Bacteria|p__Firmicutes|c__Firmicutes_unclassified	2|1239|	1.3694	
k__Bacteria|p__Firmicutes|c__Clostridia|o__Clostridiales	2|1239|186801|186802	40.10551	
k__Bacteria|p__Bacteroidetes|c__Bacteroidia|o__Bacteroidales	2|976|200643|171549	30.05768	
k__Bacteria|p__Deferribacteres|c__Deferribacteres|o__Deferribacterales	2|200930|68337|191393	28.4674	
k__Bacteria|p__Firmicutes|c__Firmicutes_unclassified|o__Firmicutes_unclassified	2|1239||	1.3694	
k__Bacteria|p__Firmicutes|c__Clostridia|o__Clostridiales|f__Clostridiaceae	2|1239|186801|186802|31979	30.80354	
k__Bacteria|p__Bacteroidetes|c__Bacteroidia|o__Bacteroidales|f__Tannerellaceae	2|976|200643|171549|2005525	30.05768	
k__Bacteria|p__Deferribacteres|c__Deferribacteres|o__Deferribacterales|f__Deferribacteraceae	2|200930|68337|191393|191394	28.4674	
k__Bacteria|p__Firmicutes|c__Clostridia|o__Clostridiales|f__Eubacteriaceae	2|1239|186801|186802|186806	9.30197	
k__Bacteria|p__Firmicutes|c__Firmicutes_unclassified|o__Firmicutes_unclassified|f__Firmicutes_unclassified	2|1239|||	1.3694	
k__Bacteria|p__Firmicutes|c__Clostridia|o__Clostridiales|f__Clostridiaceae|g__Clostridium	2|1239|186801|186802|31979|1485	30.80354	
k__Bacteria|p__Bacteroidetes|c__Bacteroidia|o__Bacteroidales|f__Tannerellaceae|g__Parabacteroides	2|976|200643|171549|2005525|375288	30.05768	
k__Bacteria|p__Deferribacteres|c__Deferribacteres|o__Deferribacterales|f__Deferribacteraceae|g__Mucispirillum	2|200930|68337|191393|191394|248038	28.4674	
k__Bacteria|p__Firmicutes|c__Clostridia|o__Clostridiales|f__Eubacteriaceae|g__Eubacterium	2|1239|186801|186802|186806|1730	9.30197	
k__Bacteria|p__Firmicutes|c__Firmicutes_unclassified|o__Firmicutes_unclassified|f__Firmicutes_unclassified|g__Firmicutes_unclassified	2|1239||||	1.3694	
k__Bacteria|p__Bacteroidetes|c__Bacteroidia|o__Bacteroidales|f__Tannerellaceae|g__Parabacteroides|s__Parabacteroides_goldsteinii	2|976|200643|171549|2005525|375288|328812	30.05768	k__Bacteria|p__Bacteroidetes|c__Bacteroidia|o__Bacteroidales|f__Tannerellaceae|g__Parabacteroides|s__Parabacteroides_sp_ASF519
k__Bacteria|p__Deferribacteres|c__Deferribacteres|o__Deferribacterales|f__Deferribacteraceae|g__Mucispirillum|s__Mucispirillum_schaedleri	2|200930|68337|191393|191394|248038|248039	28.4674	
k__Bacteria|p__Firmicutes|c__Clostridia|o__Clostridiales|f__Clostridiaceae|g__Clostridium|s__Clostridium_sp_ASF356	2|1239|186801|186802|31979|1485|97138	20.27074	
k__Bacteria|p__Firmicutes|c__Clostridia|o__Clostridiales|f__Clostridiaceae|g__Clostridium|s__Clostridium_sp_ASF502	2|1239|186801|186802|31979|1485|97139	10.53281	
k__Bacteria|p__Firmicutes|c__Clostridia|o__Clostridiales|f__Eubacteriaceae|g__Eubacterium|s__Eubacterium_plexicaudatum	2|1239|186801|186802|186806|1730|97253	9.30197	
k__Bacteria|p__Firmicutes|c__Firmicutes_unclassified|o__Firmicutes_unclassified|f__Firmicutes_unclassified|g__Firmicutes_unclassified|s__Firmicutes_bacterium_ASF500	2|1239|||||1378168	1.3694	
